import { Meal, MealTags } from './meal';

export const Meals: Meal[] = [
    {
        name: 'Tomato Soup',
        descriptionCZ: 'Rajčatová polévka',
        descriptionEN: 'Tomato soup',
        allergen: '1,7',
        priceJH: 25,
        priceTR: 25,
        photo: 'assets/TomatoSoup.jpg',
        packaging: 5,
        type: 'meal',
        class: 'menu',
    },
    {
        name: 'Chicken Soup',
        descriptionCZ: 'Kuřecí polévka',
        descriptionEN: 'Chicken Soup',
        allergen: '1,3',
        priceJH: 20,
        priceTR: 20,
        packaging: 5,
        type: 'meal',
        class: 'menu',
    },
    {
        name: 'Chicken Rara',
        descriptionCZ: 'Kuřecí kostky s jemně pálivou omáčkou',
        descriptionEN: 'Chicken nuggets with mildly hot sauce',
        heat: 1,
        allergen: '3,7',
        weight: '100g',
        priceJH: 100,
        priceTR: 110,
        photo: 'assets/Rara.jpg',
        packaging: 5,
        sideDish: {},
        tags: [MealTags.ChapatiOrRiceFree],
        type: 'meal',
        class: 'menu',
    },
    {
        name: 'Shahi Paneer',
        descriptionCZ: 'Sýrové kostky s jemně pálivou omáčkou',
        descriptionEN: 'Cheese nuggets with mildly spicy sauce',
        heat: 1,
        allergen: '1,7',
        weight: '100g',
        priceJH: 95,
        priceTR: 110,
        photo: 'assets/shahi-paneer-menu.jpg',
        packaging: 5,
        sideDish: {},
        tags: [MealTags.ChapatiOrRiceFree, MealTags.Vegetarian],
        type: 'meal',
        class: 'menu',
    },
    {
        name: 'Chicken Palak',
        descriptionCZ: 'Kuřecí kostky se špenátem',
        descriptionEN: 'Chicken nuggets with spinach',
        allergen: '1,7',
        weight: '100g',
        priceJH: 100,
        priceTR: 110,
        photo: 'assets/palak-menu.jpg',
        packaging: 5,
        sideDish: {},
        tags: [MealTags.ChapatiOrRiceFree],
        type: 'meal',
        class: 'menu',
    },
    {
        name: 'Chicken Korma',
        descriptionCZ: 'Kuřecí kostky s jemnou omáčkou',
        descriptionEN: 'Chicken nuggets with mild sauce',
        allergen: '1,7,8',
        weight: '100g',
        priceJH: 100,
        priceTR: 110,
        photo: 'assets/korma-menu.jpg',
        packaging: 5,
        sideDish: {},
        tags: [MealTags.ChapatiOrRiceFree],
        type: 'meal',
        class: 'menu',
    },
    {
        name: 'Chicken Badam Pasanda',
        descriptionCZ: 'Kuřecí kostky s jemnou omáčkou z kokosu a mandlemi',
        descriptionEN: 'Chicken nuggets with curry sauce and almonds',
        allergen: '1,7,8',
        weight: '100g',
        priceJH: 100,
        priceTR: 110,
        photo: 'assets/badam-pasanda-menu.jpg',
        packaging: 5,
        sideDish: {},
        tags: [MealTags.ChapatiOrRiceFree],
        type: 'meal',
        class: 'menu',
    },
    {
        name: 'Chicken Curry',
        descriptionCZ: 'Kuřecí kostky na kari',
        descriptionEN: 'Chicken nuggets with curry sauce',
        heat: 1,
        allergen: '1,7',
        weight: '100g',
        priceTR: 110,
        priceJH: 100,
        photo: 'assets/curry-menu.jpg',
        packaging: 5,
        sideDish: {},
        tags: [MealTags.ChapatiOrRiceFree],
        type: 'meal',
        class: 'menu',
    },
    {
        name: 'Pork Rara',
        descriptionCZ: 'Vepřové kostky s jemnou pálivou omáčkou',
        descriptionEN: 'Pork nuggets with mildly hot sauce',
        heat: 1,
        allergen: '1,3,7',
        weight: '100g',
        priceJH: 100,
        priceTR: 110,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        tags: [MealTags.ChapatiOrRiceFree],
        class: 'menu',
        photo: 'assets/Rara.jpg',
    },
    {
        name: 'Palak Paneer',
        descriptionCZ: 'Sýrové kostky se špenátem',
        descriptionEN: 'Spinach with cheese nuggets',
        allergen: '1,7',
        weight: '100g',
        priceJH: 95,
        priceTR: 110,
        photo: 'assets/palak-menu.jpg',
        packaging: 5,
        sideDish: {},
        tags: [MealTags.ChapatiOrRiceFree, MealTags.Vegetarian],
        type: 'meal',
        class: 'menu',
    },
    {
        name: 'Aloo Rajma',
        descriptionCZ: 'Brambory s fazolemi a kari omáčkou',
        descriptionEN: 'Potatoes with beans and curry sauce',
        heat: 1,
        allergen: '1,7',
        weight: '100g',
        priceJH: 95,
        priceTR: 110,
        photo: 'assets/Aloo Rajma.jpg',
        packaging: 5,
        sideDish: {},
        tags: [MealTags.ChapatiOrRiceFree, MealTags.Vegetarian],
        type: 'meal',
        class: 'menu',
    },
    {
        name: 'Lamb Kadai',
        descriptionCZ: 'Jehněčí kostky s jemně pálivou omáčkou, paprika, cibule',
        descriptionEN: 'Lamb nuggets with mildly spicy "Kadai" sauce, onions',
        heat: 1,
        allergen: '1,7',
        weight: '100g',
        priceJH: 135,
        priceTR: 135,
        photo: 'assets/kadai-menu.jpg',
        packaging: 5,
        sideDish: {},
        tags: [MealTags.ChapatiOrRiceFree],
        type: 'meal',
        class: 'menu',
    },
    {
        name: 'Paneer Badam Pasanda',
        descriptionCZ: 'Sýrové kostky s jemnou pálivou omáčkou z kokosu s mandlemi',
        descriptionEN: 'Cheese nuggets with curry sauce and almonds',
        allergen: '1,7,8',
        weight: '100g',
        priceJH: 95,
        priceTR: 110,
        photo: 'assets/badam-pasanda-menu.jpg',
        packaging: 5,
        sideDish: {},
        tags: [MealTags.ChapatiOrRiceFree, MealTags.Vegetarian],
        type: 'meal',
        class: 'menu',
    },
    {
        name: 'Dal Makhani',
        descriptionCZ: 'Indické národní jídlo – čočka',
        descriptionEN: 'Indian national food',
        allergen: '1,7',
        weight: '100g',
        priceJH: 95,
        priceTR: 110,
        photo: 'assets/dal-makhani-menu.jpg',
        packaging: 5,
        sideDish: {},
        tags: [MealTags.ChapatiOrRiceFree, MealTags.Vegetarian],
        type: 'meal',
        class: 'menu',
    },
    {
        name: 'Malai Kofta',
        descriptionCZ: 'Opečené mleté bramborové kuličky se sýrem, oříšky a jemnou omáčkou',
        descriptionEN: 'Fried mashed potatoes nuggets with chees, nuts and light sauce',
        allergen: '1,7',
        weight: '100g',
        priceJH: 95,
        priceTR: 110,
        photo: 'assets/malai-kofta.jpg',
        packaging: 5,
        sideDish: {},
        tags: [MealTags.ChapatiOrRiceFree, MealTags.Vegetarian],
        type: 'meal',
        class: 'menu',
    },
    {
        name: 'Chicken Mango',
        descriptionCZ: 'Kuřecí kostky s jemnou omáčkou z kokosu a manga',
        allergen: '1,7',
        weight: '100g',
        priceJH: 100,
        packaging: 5,
        photo: 'assets/Chicken Mango.jpg',
        sideDish: {},
        tags: [MealTags.ChapatiOrRiceFree, MealTags.New],
        type: 'meal',
        class: 'menu',
    },
    {
        name: 'Tomato Soup',
        descriptionCZ: 'Rajčatová polévka',
        descriptionEN: 'Tomato Soup',
        allergen: '1,7',
        priceJH: 25,
        priceTR: 35,
        photo: 'assets/TomatoSoup.jpg',
        packaging: 5,
        type: 'meal',
        class: 'soup',
    },
    {
        name: 'Chicken Mushroom Soup',
        descriptionCZ: 'Kuřecí polévka s houbami',
        descriptionEN: 'Chicken soup with mushrooms',
        allergen: '1,3',
        priceJH: 25,
        priceTR: 35,
        packaging: 5,
        type: 'meal',
        class: 'soup',
    },
    {
        name: 'Chicken Soup',
        descriptionCZ: 'Kuřecí polévka ',
        descriptionEN: 'Chicken soup',
        allergen: '1,3',
        priceJH: 25,
        priceTR: 35,
        packaging: 5,
        type: 'meal',
        class: 'soup',
    },
    {
        name: 'Dal Soup',
        descriptionCZ: 'Čočková polévka ',
        descriptionEN: 'Lentil soup',
        allergen: '1,7',
        priceJH: 25,
        priceTR: 35,
        packaging: 5,
        type: 'meal',
        class: 'soup',
    },
    {
        name: 'Chicken Pakora',
        descriptionCZ: 'Ostře kořeněné smažené kuřecí nugety',
        descriptionEN: 'Spicy fried chicken nuggets',
        heat: 1,
        allergen: '1',
        weight: '120g',
        priceJH: 75,
        priceTR: 80,
        packaging: 5,
        type: 'meal',
        class: 'starter',
    }, {
        name: 'Vegetarian Pakora',
        descriptionCZ: 'Smažená zelenina',
        descriptionEN: 'Fried vegetables',
        allergen: '1',
        weight: '120g',
        priceJH: 60,
        priceTR: 65,
        packaging: 5,
        tags: [MealTags.Vegetarian],
        type: 'meal',
        class: 'starter',
    }, {
        name: 'Onion Bhaji',
        descriptionCZ: 'Smažená obalovaná cibule',
        descriptionEN: 'Fried onion rings',
        allergen: '1',
        weight: '120g',
        priceJH: 60,
        priceTR: 65,
        packaging: 5,
        type: 'meal',
        class: 'starter',
        photo: 'assets/onion bhaji.jpg',
    }, {
        name: 'Papadum',
        descriptionCZ: 'Křupavá placka chips, Indická specialita',
        descriptionEN: 'Indian speciality',
        allergen: '1',
        weight: '10g',
        priceJH: 15,
        type: 'meal',
        class: 'starter',
    }, {
        name: 'Tandoori Mix grill',
        descriptionCZ: 'Grilované krevety, kuřecí a jehněčí maso a 2 druhy chutney',
        descriptionEN: 'Grilled prawns, chicken and lamb meat',
        allergen: '',
        weight: '300g',
        priceJH: 310,
        priceTR: 310,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'tandoor',
    }, {
        name: 'Lamb Tikka',
        descriptionCZ: 'Grilované ostře kořeněné jehněčí kostky a 2 druhy chutney',
        descriptionEN: 'Grilled spicy lamb nuggets',
        heat: 1,
        allergen: '',
        weight: '220g',
        priceJH: 215,
        priceTR: 225,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'tandoor',
        photo: 'assets/lamb tikka.jpg',
    }, {
        name: 'Tandoori Gateway Of India',
        descriptionCZ: 'Grilované ostře kořeněné kuřecí kostky a stehno a 2 druhy chutney',
        descriptionEN: 'Grilled hot chicken nuggets and chicken leg',
        heat: 1,
        allergen: '',
        weight: '220g',
        priceJH: 170,
        priceTR: 175,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'tandoor',
    }, {
        name: 'Tandoori Shish Kabab',
        descriptionCZ: 'Mleté a grilované jehněčí maso a 2 druhy chutney',
        descriptionEN: 'Ground lamb meat',
        allergen: '',
        weight: '220g',
        priceJH: 175,
        priceTR: 185,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'tandoor',
        photo: 'assets/tandori shish kabab.jpg',
    }, {
        name: 'Chicken Saslik',
        descriptionCZ: 'Grilované kuřecí kostky, grilovaná cibule a rajčata a 2 druhy chutney',
        descriptionEN: 'Grilled chicken nuggets with tomatoes and onion',
        allergen: '',
        weight: '220g',
        priceJH: 175,
        priceTR: 175,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'tandoor',
        photo: 'assets/chicken saslik.jpg',
    }, {
        name: 'Chicken Malaj Kabab',
        descriptionCZ: 'Kuřecí kostky marinované ve smetaně s kešu oříšky a 2 druhy chutney',
        descriptionEN: 'Chicken nuggets marinated in cream with cashew nut',
        allergen: '7,8',
        weight: '220g',
        priceJH: 175,
        priceTR: 175,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'tandoor',
        photo: 'assets/chicken malaj kabab.jpg',
    }, {
        name: 'Chicken Kastoori Kabab',
        descriptionCZ: 'Jemně kořeněné a grilované kuřecí kostky a 2 druhy chutney',
        descriptionEN: 'Grilled spicy chicken nuggets',
        allergen: '',
        weight: '220g',
        priceJH: 165,
        priceTR: 175,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'tandoor',
    }, {
        name: 'Chicken Tandoori',
        descriptionCZ: 'Grilované ostře kořeněné kuřecí stehno a prsa a 2 druhy chutney',
        descriptionEN: 'Grilled spicy Chicken leg and breast',
        heat: 1,
        allergen: '',
        weight: '220g',
        priceJH: 165,
        priceTR: 175,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'tandoor',
        photo: 'assets/chicken tandoori.jpg',
    }, {
        name: 'Chicken Tikka',
        descriptionCZ: 'Ostře kořeněné a grilované kuřecí kostky a 2 druhy chutney',
        descriptionEN: 'Grilled hot chicken nuggets',
        heat: 1,
        allergen: '',
        weight: '220g',
        priceJH: 165,
        priceTR: 175,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'tandoor',
        photo: 'assets/chicken tika.jpg',
    }, {
        name: 'Pork Saslik',
        descriptionCZ: 'Grilované vepřové kostky, grilovaná cibule a rajčata a 2 druhy chutney',
        descriptionEN: 'Grilled pork nuggets with tomato and onion',
        allergen: '',
        weight: '220g',
        priceJH: 175,
        priceTR: 175,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'tandoor',
        photo: 'assets/chicken saslik.jpg',
    }, {
        name: 'Pork Tikka',
        descriptionCZ: 'Ostře kořeněné grilované vepřové kostky a 2 druhy chutney',
        descriptionEN: 'Grilled hot pork nuggets',
        heat: 1,
        allergen: '',
        weight: '220g',
        priceJH: 165,
        priceTR: 175,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'tandoor',
        photo: 'assets/pork tikka.jpg',
    }, {
        name: 'Green Chicken Tikka',
        descriptionCZ: 'Velmi ostře grilované zelené kuřecí kostky a 2 druhy chutney',
        descriptionEN: 'Grilled hot green chicken nuggets',
        heat: 2,
        allergen: '',
        weight: '200g',
        priceJH: 165,
        priceTR: 175,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'tandoor',
    }, {
        name: 'Paneer Saslik',
        descriptionCZ: 'Grilované sýrové kostky, grilovaná cibule a rajčata a 2 druhy chutney.',
        descriptionEN: 'Grilled chicken nuggets with tomatoes and onion',
        allergen: '1,7',
        weight: '200g',
        priceJH: 145,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'vege',
        tags: [MealTags.New, MealTags.Vegetarian, MealTags.ChefSpecial],
        photo: 'assets/chicken saslik.jpg',
    }, {
        name: 'Chicken Thali',
        descriptionCZ: 'Kuřecí kostky, špenát, míchaná zelenina (fazole, hrášek, květák, brambory, mrkev, sýr)',
        descriptionEN: 'Chicken nuggets, spinach, beans, peas, cauliflower, potatoes, carrots, cheese',
        allergen: '1,7',
        weight: '200g',
        priceJH: 170,
        priceTR: 175,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'chicken',
        photo: 'assets/thali.jpg',
    }, {
        name: 'Chicken Mushroom',
        descriptionCZ: 'Kuřecí kostky se žampiony v omáčce',
        descriptionEN: 'Chicken nuggets with mushrooms in sauce',
        allergen: '7',
        weight: '200g',
        priceJH: 155,
        priceTR: 160,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'chicken',
    }, {
        name: 'Chicken Tikka Masala',
        descriptionCZ: 'Grilované kuřecí kostky  s ostrou omáčkou',
        descriptionEN: 'Grilled chicken nuggets with hot sauce',
        heat: 1,
        allergen: '7',
        weight: '200g',
        priceJH: 155,
        priceTR: 160,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'chicken',
        photo: 'assets/chicken-tikka-masala.jpg',
    }, {
        name: 'Chicken Chana',
        descriptionCZ: 'Kuřecí kostky s cizrnou',
        descriptionEN: 'Chicken nuggets with indian peas',
        allergen: '7',
        weight: '200g',
        priceJH: 155,
        priceTR: 160,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'chicken',
        photo: 'assets/chana.jpg',
    }, {
        name: 'Chicken Dabal Maza',
        descriptionCZ: 'Kuřecí kostky s jemně kořeněnou restovanou zeleninou',
        descriptionEN: 'Chicken nuggets with mildly spicy vegetable',
        allergen: '7',
        weight: '200g',
        priceJH: 155,
        priceTR: 160,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'chicken',
    }, {
        name: 'Chicken Kadai',
        descriptionCZ: 'Kuřecí kostky s jemně pálivou omáčkou Kadai, paprika, cibule',
        descriptionEN: 'Chicken nuggets with mildly spicy "Kadai" sauce',
        heat: 1,
        allergen: '7',
        weight: '200g',
        priceJH: 155,
        priceTR: 160,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'chicken',
        photo: 'assets/Lamb Kadai.jpg',
    }, {
        name: 'Chicken Jalfrezi',
        descriptionCZ: 'Kuřecí kostky s jemnou omáčkou s cibulí, paprikou a rajčaty',
        descriptionEN: 'Chicken nuggets with vegetables',
        allergen: '7',
        weight: '200g',
        priceJH: 155,
        priceTR: 160,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'chicken',
        photo: 'assets/chicken jalfrezi.jpg',
    }, {
        name: 'Chicken Palak',
        descriptionCZ: 'Kuřecí kostky se špenátem',
        descriptionEN: 'Chicken nuggets with spinach',
        allergen: '7',
        weight: '200g',
        priceJH: 155,
        priceTR: 160,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'chicken',
        photo: 'assets/Palak.jpg',
    }, {
        name: 'Chicken Badam Pasanda',
        descriptionCZ: 'Kuřecí kostky s jemnou omáčkou z kokosu s mandlemi',
        descriptionEN: 'Chicken nuggets with curry sauce and almonds',
        allergen: '7,8',
        weight: '200g',
        priceJH: 155,
        priceTR: 160,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'chicken',
        photo: 'assets/badam-pasanda.jpg',
    }, {
        name: 'Chicken Rara',
        descriptionCZ: 'Kuřecí kostky s jemně pálivou omáčkou',
        descriptionEN: 'Chicken nuggets with mildly hot sauce',
        heat: 1,
        allergen: '3,7',
        weight: '200g',
        priceJH: 155,
        priceTR: 160,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'chicken',
        photo: 'assets/Rara.jpg',
    }, {
        name: 'Butter Chicken',
        descriptionCZ: 'Kuřecí kostky s pikantní máslovou omáčkou',
        descriptionEN: 'Chicken nuggets with hot butter sauce',
        allergen: '7',
        weight: '200g',
        priceJH: 155,
        priceTR: 160,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'chicken',
        photo: 'assets/butter chicken.jpg',
    }, {
        name: 'Chicken Vindaloo',
        descriptionCZ: 'Kuřecí kostky s bramborami a velmi ostrou omáčkou',
        descriptionEN: 'Chicken nuggets and potatoes with very hot sauce',
        heat: 3,
        allergen: '',
        weight: '200g',
        priceJH: 155,
        priceTR: 160,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'chicken',
        photo: 'assets/vindaloo.jpg',
    }, {
        name: 'Chicken Korma',
        descriptionCZ: 'Kuřecí kostky s jemnou omáčkou',
        descriptionEN: 'Chicken nuggets with mild sauce',
        allergen: '7,8',
        weight: '200g',
        priceJH: 155,
        priceTR: 160,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'chicken',
        photo: 'assets/Korma.jpg',
    }, {
        name: 'Chicken Dal',
        descriptionCZ: 'Kuřecí kostky s kari čočkou',
        descriptionEN: 'Chicken nuggets with indian lentil',
        allergen: '7',
        weight: '200g',
        priceJH: 155,
        priceTR: 160,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'chicken',
    }, {
        name: 'Chicken Curry',
        descriptionCZ: 'Kuřecí kostky s kari omáčkou',
        descriptionEN: 'Chicken nuggets with curry sauce',
        heat: 1,
        allergen: '7',
        weight: '200g',
        priceJH: 155,
        priceTR: 160,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'chicken',
        photo: 'assets/Curry.jpg',
    }, {
        name: 'Labbader Chicken',
        descriptionCZ: 'Kuřecí kostky s kari omáčkou a jemně krájenou papričkou a kešu',
        descriptionEN: 'Chicken nuggets with curry sauce and finely sliced pepper and cashew nuts',
        allergen: '7,8',
        weight: '200g',
        priceJH: 155,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        tags: [MealTags.New, MealTags.ChefSpecial],
        class: 'lamb',
    }, {
        name: 'Lamb Thali',
        descriptionCZ: 'Kořeněné jehněčí kostky, špenát, míchaná zelenina (fazole, hrášek, květák, brambory, mrkev, sýr)',
        descriptionEN: 'Lamb nuggets, spinach, beans, peas, cauliflower, potatoes, carrots, cheese',
        allergen: '1,7',
        weight: '200g',
        priceJH: 190,
        priceTR: 195,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'lamb',
        photo: 'assets/thali.jpg',
    }, {
        name: 'Lamb Mushroom',
        descriptionCZ: 'Jehněčí kostky v houbové omáčce',
        descriptionEN: 'Lamb nuggets with mushrooms in sauce',
        allergen: '7',
        weight: '200g',
        priceJH: 180,
        priceTR: 180,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'lamb',
    }, {
        name: 'Lamb Masala',
        descriptionCZ: 'Jehněčí kostky s ostrou omáčkou',
        descriptionEN: 'Lamb nuggets with hot sauce',
        heat: 1,
        allergen: '7',
        weight: '200g',
        priceJH: 180,
        priceTR: 180,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'lamb',
        photo: 'assets/masala.jpg',
    }, {
        name: 'Lamb Kadai',
        descriptionCZ: 'Jehněčí kostky s jemně pálivou omáčkou Kadai, paprika, cibule',
        descriptionEN: 'Lamb nuggets with mildly spicy "Kadai" sauce',
        heat: 1,
        allergen: '7',
        weight: '200g',
        priceJH: 180,
        priceTR: 180,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'lamb',
        photo: 'assets/Lamb Kadai.jpg',
    }, {
        name: 'Lamb Palak',
        descriptionCZ: 'Jehněčí kostky se špenátem',
        descriptionEN: 'Lamb nuggets with spinach',
        allergen: '7',
        weight: '200g',
        priceJH: 180,
        priceTR: 180,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'lamb',
        photo: 'assets/Palak.jpg',
    }, {
        name: 'Lamb Badam Pasanda',
        descriptionCZ: 'Jehněčí kostky s jemnou omáčkou z kokosu s mandlemi',
        descriptionEN: 'Lamb nuggets with curry sauce and almonds',
        allergen: '7,8',
        weight: '200g',
        priceJH: 180,
        priceTR: 180,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'lamb',
        photo: 'assets/badam-pasanda.jpg',
    }, {
        name: 'Lamb Vindaloo',
        descriptionCZ: 'Jehněčí kostky s bramborami a velmi ostrou omáčkou',
        descriptionEN: 'Lamb nuggets and potatoes with very hot sauce',
        heat: 3,
        allergen: '',
        weight: '200g',
        priceJH: 180,
        priceTR: 180,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'lamb',
        photo: 'assets/vindaloo.jpg',
    }, {
        name: 'Lamb Curry',
        descriptionCZ: 'Jehněčí kostky s kari omáčkou',
        descriptionEN: 'Lamb nuggets with curry sauce',
        heat: 1,
        allergen: '7',
        weight: '200g',
        priceJH: 180,
        priceTR: 180,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'lamb',
        photo: 'assets/Curry.jpg',
    }, {
        name: 'Lamb Rara',
        descriptionCZ: 'Jehněčí kostky s jemně pálivou omáčkou',
        descriptionEN: 'Lamb nuggets with mildly hot sauce',
        heat: 1,
        allergen: '3,7',
        weight: '200g',
        priceJH: 180,
        priceTR: 180,
        packaging: 5,
        photo: 'assets/Rara.jpg',
        sideDish: {},
        type: 'meal',
        class: 'lamb',
    }, {
        name: 'Pork Vindaloo',
        descriptionCZ: 'Vepřové kostky s bramborami a velmi ostrou omáčkou',
        descriptionEN: 'Pork nuggets and potatoes with very hot sauce',
        heat: 3,
        allergen: '',
        weight: '200g',
        priceJH: 160,
        priceTR: 165,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'pork',
        photo: 'assets/vindaloo.jpg',
    }, {
        name: 'Pork Curry',
        descriptionCZ: 'Vepřové kostky s kari omáčkou',
        descriptionEN: 'Pork nuggets with curry sauce',
        heat: 1,
        allergen: '7',
        weight: '200g',
        priceJH: 160,
        priceTR: 165,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'pork',
        photo: 'assets/Curry.jpg',
    }, {
        name: 'Pork Kadai',
        descriptionCZ: 'Vepřové kostky s jemně pálivou omáčkou Kadai, paprika, cibule',
        descriptionEN: 'Pork nuggets with mildly hot "Kadai" sauce',
        heat: 1,
        allergen: '7',
        weight: '200g',
        priceJH: 160,
        priceTR: 165,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'pork',
        photo: 'assets/Lamb Kadai.jpg',
    }, {
        name: 'Pork Mushroom',
        descriptionCZ: 'Vepřové kostky v houbové omáčce',
        descriptionEN: 'Pork nuggets with mushroom in sauce',
        allergen: '7',
        weight: '200g',
        priceJH: 160,
        priceTR: 165,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'pork',
    }, {
        name: 'Pork Rara',
        descriptionCZ: 'Vepřové kostky s jemně pálivou omáčkou',
        descriptionEN: 'Pork nuggets with mildly hot sauce',
        heat: 1,
        allergen: '3,7',
        weight: '200g',
        priceJH: 160,
        priceTR: 165,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'pork',
        photo: 'assets/Rara.jpg',
    }, {
        name: 'Vegetarian Thali',
        descriptionCZ: 'Indická čočka, špenát, míchaná zelenina (fazole, hrášek, květák, sýr, brambory, mrkev)',
        descriptionEN: 'Mixed vegetables, spinach, beans, peas, cauliflower, potatoes, carrots, cheese',
        allergen: '1,7',
        weight: '200g',
        priceJH: 155,
        priceTR: 160,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'vege',
        photo: 'assets/thali.jpg',
    }, {
        name: 'Paneer Badam Pasanda',
        descriptionCZ: 'Sýrové kostky s jemnou omáčkou z kokosu s mandlemi',
        descriptionEN: 'Cheese nuggets with curry sauce and almonds',
        allergen: '1,7,8',
        weight: '200g',
        priceJH: 145,
        priceTR: 140,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'vege',
        photo: 'assets/badam-pasanda.jpg',
    }, {
        name: 'Shahi Paneer',
        descriptionCZ: 'Sýrové kostky s jemně pálivou omáčkou',
        descriptionEN: 'Cheese nuggets with mildly spicy sauce',
        heat: 1,
        allergen: '1,7',
        weight: '200g',
        priceJH: 145,
        priceTR: 140,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'vege',
        photo: 'assets/Shahi Paneer.jpg',
    }, {
        name: 'Palak Paneer',
        descriptionCZ: 'Sýrové kostky se špenátem',
        descriptionEN: 'Spinach with cheese nuggets',
        allergen: '1,7',
        weight: '200g',
        priceJH: 145,
        priceTR: 140,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'vege',
        photo: 'assets/Palak Paneer.jpg',
    }, {
        name: 'Paneer Korma',
        descriptionCZ: 'Sýrové kostky s jemnou omáčkou',
        descriptionEN: 'Cheese nuggets with mild sauce',
        allergen: '1,7,8',
        weight: '200g',
        priceJH: 145,
        priceTR: 140,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'vege',
        photo: 'assets/Korma.jpg',
    }, {
        name: 'Kadai Paneer',
        descriptionCZ: 'Sýrové kostky s jemně pálivou omáčkou Kadai, paprika, cibule',
        descriptionEN: 'Cheese nuggets with mildly spicy "Kadai" sauce',
        heat: 1,
        allergen: '1,7',
        weight: '200g',
        priceJH: 145,
        priceTR: 140,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'vege',
        photo: 'assets/Lamb Kadai.jpg',
    }, {
        name: 'Dal Palak',
        descriptionCZ: 'Špenát se žlutým hrachem',
        descriptionEN: 'Lentil with spinach',
        allergen: '7',
        weight: '200g',
        priceJH: 135,
        priceTR: 140,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'vege',
        photo: 'assets/dal palak.jpg',
    }, {
        name: 'Mattar Mushroom',
        descriptionCZ: 'Žampióny s hráškem ve velmi ostré omáčce',
        descriptionEN: 'Mushroom with peas in very hot sauce',
        heat: 2,
        allergen: '7',
        weight: '200g',
        priceJH: 135,
        priceTR: 140,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'vege',
    }, {
        name: 'Rajma Masala',
        descriptionCZ: 'Indické fazole s ostrou omáčkou',
        descriptionEN: 'Indian beans with Hot sauce',
        heat: 1,
        allergen: '7',
        weight: '200g',
        priceJH: 135,
        priceTR: 140,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'vege',
        photo: 'assets/Aloo Rajma.jpg',
    }, {
        name: 'Vegetarian Vindaloo',
        descriptionCZ: 'Míchaná zelenina (fazole, květák, mrkev, sýr, brambory, hrášek) velmi ostrá omáčka s bramborami',
        descriptionEN: 'Mixed vegetables with very Hot sauce',
        heat: 3,
        allergen: '',
        weight: '200g',
        priceJH: 135,
        priceTR: 140,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'vege',
        photo: 'assets/vindaloo.jpg',
    }, {
        name: 'Vegetarian Korma',
        descriptionCZ: 'Míchaná zelenina (fazole, květák, mrkev, brambory hrášek, sýr) jemná omáčka s kokosem a kešu oříšky',
        descriptionEN: 'Mixed vegetable in mild sauce with coconut and almonds',
        allergen: '7,8',
        weight: '200g',
        priceJH: 135,
        priceTR: 140,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'vege',
        photo: 'assets/Korma.jpg',
    }, {
        name: 'Dal Makhani',
        descriptionCZ: 'Indické národní jídlo, čočka',
        descriptionEN: 'Indian national food',
        allergen: '7',
        weight: '200g',
        priceJH: 135,
        priceTR: 140,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'vege',
        photo: 'assets/Dal Makhani.jpg',
    }, {
        name: 'Bombay Aloo',
        descriptionCZ: 'Brambory s indickým kořením',
        descriptionEN: 'Potatoes with spice',
        allergen: '7',
        weight: '200g',
        priceJH: 135,
        priceTR: 140,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'vege',
    }, {
        name: 'Aloo Palak',
        descriptionCZ: 'Brambory se špenátem',
        descriptionEN: 'Potatoes with spinach',
        allergen: '7',
        weight: '200g',
        priceJH: 135,
        priceTR: 140,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'vege',
        photo: 'assets/Palak.jpg',
    }, {
        name: 'Plain Palak',
        descriptionCZ: 'Pikantní špenát',
        descriptionEN: 'Spicy spinach',
        heat: 1,
        allergen: '7',
        weight: '200g',
        priceJH: 135,
        priceTR: 140,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'vege',
        photo: 'assets/plain palak.jpg',
    }, {
        name: 'Aloo Rajma',
        descriptionCZ: 'Brambory s fazolemi a kari omáčkou',
        descriptionEN: 'Potatoes with beans and curry sauce',
        heat: 1,
        allergen: '7',
        weight: '200g',
        priceJH: 135,
        priceTR: 140,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'vege',
        photo: 'assets/Aloo Rajma.jpg',
    }, {
        name: 'Mix Vegetables',
        descriptionCZ: 'Kořeněná míchaná zelenina (fazole, hrášek, květák, sýr, brambory, mrkev)',
        descriptionEN: 'Mixed vegetable with mild spice',
        allergen: '7',
        weight: '200g',
        priceJH: 135,
        priceTR: 140,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'vege',
    }, {
        name: 'Malai Kofta',
        descriptionCZ: 'Opečené mleté bramborové kuličky se sýrem, oříšky a jemnou omáčkou',
        descriptionEN: 'Fried mashed potatoes nuggets with chees, nuts and light sauce',
        allergen: '7,8',
        weight: '200g',
        priceJH: 145,
        priceTR: 140,
        photo: 'assets/malai-kofta.jpg',
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'vege',
    }, {
        name: 'Shahi kofta',
        descriptionCZ: 'Opečené mleté bramborové kuličky se sýrem, oříšky a pikantní omáčkou',
        descriptionEN: 'Fried mashed potatoes nuggets with chees, nuts and piquant sauce',
        heat: 1,
        allergen: '7,8',
        weight: '200g',
        priceJH: 145,
        priceTR: 140,
        photo: 'assets/malai-kofta.jpg',
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'vege',
    }, {
        name: 'Palak Kofta',
        descriptionCZ: 'Opečené mleté bramborové kuličky se sýrem, oříšky a špenátem',
        descriptionEN: 'Fried mashed potatoes nuggets with chees, nuts and spinach',
        allergen: '7,8',
        weight: '200g',
        priceJH: 145,
        priceTR: 140,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'vege',
    }, {
        name: 'Chana Masala',
        descriptionCZ: 'Cizrna s pikantní omáčkou',
        descriptionEN: 'Peas with spicy sauce',
        heat: 1,
        allergen: '7,8',
        weight: '200g',
        priceJH: 135,
        priceTR: 140,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'vege',
        photo: 'assets/chana.jpg',
    }, {
        name: 'Fish Masala',
        descriptionCZ: 'Kousky ryby v ostré omáčce',
        descriptionEN: 'Fish pieces with hot sauce',
        heat: 1,
        allergen: '4,7',
        weight: '200g',
        priceJH: 155,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'fish',
        photo: 'assets/masala.jpg',
    }, {
        name: 'Fish Curry',
        descriptionCZ: 'Ryba s kari omáčkou',
        descriptionEN: 'Fish with curry sauce',
        heat: 1,
        allergen: '4,7',
        weight: '200g',
        priceJH: 155,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'fish',
        photo: 'assets/Curry.jpg',
    }, {
        name: 'Rara Fish',
        descriptionCZ: 'Ryba s jemně pálivou omáčkou',
        descriptionEN: 'Fish nuggets with mildly hot sauce',
        heat: 1,
        allergen: '3,4,7',
        weight: '200g',
        priceJH: 155,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'fish',
        photo: 'assets/Rara.jpg',
    }, {
        name: 'Fish Vindaloo',
        descriptionCZ: 'Ryba s velmi pálivou omáčkou a s bramborami',
        descriptionEN: 'Fish pieces with very hot sauce',
        heat: 3,
        allergen: '4',
        weight: '200g',
        priceJH: 155,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'fish',
        photo: 'assets/vindaloo.jpg',
    }, {
        name: 'Fish Badam Pasanda',
        descriptionCZ: 'Ryba s jemnou omáčkou z kokosu a s mandlemi',
        descriptionEN: 'Fish with sweet curry sauce and almonds',
        allergen: '4,7,8',
        weight: '200g',
        priceJH: 155,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'fish',
        photo: 'assets/badam-pasanda.jpg',
    }, {
        name: 'Fish Korma',
        descriptionCZ: 'Ryba s jemnou omáčkou',
        descriptionEN: 'Fish with mild sauce',
        allergen: '4,7,8',
        weight: '200g',
        priceJH: 155,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'fish',
        photo: 'assets/Korma.jpg',
    }, {
        name: 'Prawn Vindaloo',
        descriptionCZ: 'Krevety ve velmi ostré omáčce s bramborami',
        descriptionEN: 'Prawn in very hot sauce with potatoes',
        heat: 3,
        allergen: '',
        weight: '200g',
        priceJH: 175,
        priceTR: 180,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'fish',
        photo: 'assets/vindaloo.jpg',
    }, {
        name: 'Lumbini Palau',
        descriptionCZ: 'Krevety, směs rýže a míchané zeleniny',
        descriptionEN: 'Prawn, mixed vegetable with indian rice',
        allergen: '8',
        weight: '200g',
        priceJH: 155,
        priceTR: 180,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'fish',
    }, {
        name: 'Prawn Badam Pasanda',
        descriptionCZ: 'Krevety s jemnou omáčkou z kokosu a s mandlemi',
        descriptionEN: 'Prawn with curry sauce and almonds',
        allergen: '7,8',
        weight: '200g',
        priceJH: 175,
        priceTR: 180,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'fish',
        photo: 'assets/badam-pasanda.jpg',
    }, {
        name: 'Prawn Masala',
        descriptionCZ: 'Krevety s ostrou omáčkou',
        descriptionEN: 'Prawn with hot sauce',
        heat: 1,
        allergen: '7',
        weight: '200g',
        priceJH: 175,
        priceTR: 180,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'fish',
        photo: 'assets/masala.jpg',
    }, {
        name: 'Prawn Curry',
        descriptionCZ: 'Krevety s kari omáčkou',
        descriptionEN: 'Prawn with curry sauce',
        heat: 1,
        allergen: '7',
        weight: '200g',
        priceJH: 175,
        priceTR: 180,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'fish',
        photo: 'assets/Curry.jpg',
    }, {
        name: 'Prawn Kadai',
        descriptionCZ: 'Krevety s jemně pálivou omáčkou Kadai, paprika, cibule',
        descriptionEN: 'Prawn with mildly spicy "Kadai" sauce',
        heat: 1,
        allergen: '7',
        weight: '200g',
        priceJH: 175,
        priceTR: 180,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'fish',
        photo: 'assets/Lamb Kadai.jpg',
    }, {
        name: 'Lamb Biryani',
        descriptionCZ: 'Indická rýže s jehněčími kostkami',
        descriptionEN: 'Indian rice with lamb nuggets',
        allergen: '7,8',
        weight: '250g',
        priceJH: 180,
        priceTR: 185,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'biryani',
        photo: 'assets/Chicken Birianes.jpg'
    }, {
        name: 'Pork Biryani',
        descriptionCZ: 'Indická rýže s vepřovými kostkami',
        descriptionEN: 'Indian rice with pork nuggets',
        allergen: '7,8',
        weight: '250g',
        priceJH: 160,
        priceTR: 185,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'biryani',
        photo: 'assets/Chicken Birianes.jpg'
    }, {
        name: 'Chicken Biryani',
        descriptionCZ: 'Indická rýže s kuřecími kostkami',
        descriptionEN: 'Indian rice with chicken nuggets',
        allergen: '7,8',
        weight: '250g',
        priceJH: 155,
        priceTR: 160,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'biryani',
        photo: 'assets/Chicken Birianes.jpg'
    }, {
        name: 'Vegetarian Biryani',
        descriptionCZ: 'Indická rýže s míchanou zeleninou',
        descriptionEN: 'Indian rice with mixed vegetable',
        allergen: '7,8',
        weight: '250g',
        priceJH: 140,
        priceTR: 140,
        packaging: 5,
        sideDish: {},
        type: 'meal',
        class: 'biryani',
        photo: 'assets/Chicken Birianes.jpg'
    },
    {
        name: 'Tandoori Chapati',
        descriptionCZ: 'Indická placka',
        allergen: '1',
        priceJH: 0,
        priceTR: 0,
        type: 'side',
        class: 'menu',
    },
    {
        name: 'Plain Rice',
        descriptionCZ: 'Indická rýže',
        weight: '100g',
        priceJH: 0,
        priceTR: 0,
        packaging: 5,
        type: 'side',
        class: 'menu',
        photo: 'assets/rice.jpg',

    },
    {
        name: 'Tandoori Kulcha',
        descriptionCZ: 'Placka plněná bramborami a sýrem',
        descriptionEN: 'Stuffed indian bread with potatoes and cheese',
        allergen: '1',
        priceJH: 25,
        priceTR: 25,
        type: 'side',
        class: 'menu',
        photo: 'assets/kulcha.jpg',
    },
    {
        name: 'Tandoori Garlic Kulcha',
        descriptionCZ: 'Placka plněná směsí brambor a sýra s česnekem',
        allergen: '1',
        priceJH: 25,
        priceTR: 25,
        type: 'side',
        class: 'menu',
        photo: 'assets/kulcha.jpg',
    },
    {
        name: 'Tandoori Chapati',
        descriptionCZ: 'Indická základní placka',
        descriptionEN: 'Basic indian bread',
        allergen: '1',
        priceJH: 25,
        priceTR: 25,
        type: 'side',
        class: 'side',
        photo: 'assets/Chapati.jpg',
    },
    {
        name: 'Basmati Rice',
        descriptionCZ: 'Indická rýže Basmati',
        descriptionEN: 'Basmati Rice',
        allergen: '',
        packaging: 5,
        priceJH: 35,
        priceTR: 35,
        type: 'side',
        class: 'side',
        photo: 'assets/rice.jpg',
    },
    {
        name: 'Tandoori Kulcha',
        descriptionCZ: 'Placka plněná bramborami a sýrem',
        descriptionEN: 'Stuffed indian bread with potatoes and cheese',
        allergen: '1',
        priceJH: 50,
        priceTR: 50,
        type: 'side',
        class: 'side',
        photo: 'assets/kulcha.jpg',
    },
    {
        name: 'Jeera Chawal',
        descriptionCZ: 'Indická rýže Basmati s římským kmínem',
        descriptionEN: 'Indian rice with Cumin',
        allergen: '',
        packaging: 5,
        priceJH: 35,
        priceTR: 40,
        type: 'side',
        class: 'side',
        photo: 'assets/jeera chawal.jpg',
    },
    {
        name: 'Peas Rice',
        descriptionCZ: 'Indická rýže s hráškem',
        descriptionEN: 'Indian rice with peas',
        allergen: '',
        packaging: 5,
        priceJH: 35,
        priceTR: 40,
        type: 'side',
        class: 'side',
        photo: 'assets/peas rice.jpg',
    },
    {
        name: 'Tandoori Garlic Kulcha',
        descriptionCZ: 'Placka plněná směsí brambor a sýra s česnekem',
        descriptionEN: 'Stufed indian bread with potatoes, cheese, garlic',
        allergen: '1',
        priceJH: 50,
        priceTR: 50,
        type: 'side',
        class: 'side',
        photo: 'assets/kulcha.jpg',
    },
    {
        name: 'Tandoori Garlic Nan',
        descriptionCZ: 'Indická placka s česnekem',
        descriptionEN: 'Indian bread with garlic',
        allergen: '1',
        priceJH: 40,
        priceTR: 40,
        type: 'side',
        class: 'side',
        photo: 'assets/tandori garlic nan.jpg',
    },
    {
        name: 'Tandoori Punjabi Nan',
        descriptionCZ: 'Indická placka s oříšky',
        descriptionEN: 'Indian bread with nuts',
        allergen: '1,8',
        priceJH: 40,
        priceTR: 40,
        type: 'side',
        class: 'side',
        photo: 'assets/Chapati.jpg',
    },
    {
        name: 'Tandoori Protha',
        descriptionCZ: 'Indická národní placka s bylinkami',
        descriptionEN: 'ndian national bread',
        allergen: '1',
        priceJH: 40,
        priceTR: 40,
        type: 'side',
        class: 'side',
        photo: 'assets/tandori protha.jpg',
    },
    {
        name: 'Tandoori Nan',
        descriptionCZ: 'Indické placky sypané mákem a potřené ghee',
        descriptionEN: 'Indian bread with butter',
        allergen: '1',
        priceJH: 30,
        priceTR: 35,
        type: 'side',
        class: 'side',
        photo: 'assets/Chapati.jpg',
    },
    {
        name: 'Lassi Koktejl',
        descriptionCZ: 'V indii velmi populární osvěžující jogurtový nápoj. Mùžete si vybrat mango, sladkou nebo slanou variantu.',
        allergen: '7',
        priceJH: 40,
        priceTR: 40,
        type: 'meal',
        class: 'drink',
        photo: 'assets/lassi.jpg',
    },
    {
        name: 'Ginger Beer',
        descriptionCZ: 'Zázvorová limonáda',
        priceJH: 45,
        priceTR: 45,
        type: 'meal',
        class: 'drink',
        photo: 'assets/ginger-beer.jpg',
    },
    {
        name: 'Bílý chai Dátá Masala',
        descriptionCZ: 'Tradiční indický čaj s mlékem a kořením',
        allergen: '7',
        priceJH: 40,
        priceTR: 40,
        type: 'meal',
        class: 'drink',
        photo: 'assets/chai.jpg',
    },
    {
        name: 'Točené pivo Regent 11°',
        descriptionCZ: 'Jen málokterý pivovar ve střední Evropě se může pochlubit takovou tradicí jako třeboňský pivovar, který byl založen roku 1379.',
        allergen: '1',
        priceJH: 35,
        priceTR: 35,
        type: 'meal',
        class: 'drink',
        photo: 'assets/regent.jpg',
    }
];
