import { Meal } from './meal';

export const Menu: Meal[] = [
    {
        name: 'Chicken Rara',
        description: 'Kuřecí kostky s jemně pálivou omáčkou, indická rýže nebo indické placky',
        allergen: '1,3,7,',
        weight: '100g',
        price: 100,
        photo: 'assets/Rara.jpg',
        packaging: 5,
    },
    {
        name: 'Shahi Paneer',
        description: 'Sýrové kostky s jemně pálivou omáčkou, indická rýže nebo indické placky',
        allergen: '1,7',
        weight: '100g',
        price: 95,
        photo: 'assets/Shahi Paneer.jpg',
        packaging: 5,
    },
    {
        name: 'Chicken Palak',
        description: 'Kuřecí kostky se špenátem, indická rýže nebo indické placky',
        allergen: '1,7',
        weight: '100g',
        price: 100,
        photo: 'assets/Palak.jpg',
        packaging: 5,
    },
    {
        name: 'Chicken Korma',
        description: 'Kuřecí kostky s jemnou omáčkou, indická rýže nebo indické placky',
        allergen: '1,7,8,',
        weight: '100g',
        price: 100,
        photo: 'assets/Korma.jpg',
        packaging: 5,
    },
    {
        name: 'Chicken Badam Pasanda',
        description: 'Kuřecí kostky s jemnou omáčkou z kokosu a mandlemi, indická rýže nebo indické placky',
        allergen: '1,7,8',
        weight: '100g',
        price: 100,
        photo: 'assets/Chicken Badam Pasanda.jpg',
        packaging: 5,
    },
    {
        name: 'Chicken Curry',
        description: 'Kuřecí kostky na kari, indická rýže nebo indické placky',
        allergen: '1,7',
        weight: '100g',
        price: 100,
        photo: 'assets/Curry.jpg',
        packaging: 5,
    },
    {
        name: 'Pork Rara',
        description: 'Vepřové kostky s jemnou pálivou omáčkou, indická rýže nebo indické placky',
        allergen: '1,3,7,',
        weight: '100g',
        price: 100,
        photo: 'assets/Pork Rara.jpg',
        packaging: 5,
    },
    {
        name: 'Palak Paneer',
        description: 'Sýrové kostky se špenátem, indická rýže nebo indické placky',
        allergen: '1,7',
        weight: '100g',
        price: 95,
        photo: 'assets/Palak Paneer.jpg',
        packaging: 5,
    },
    {
        name: 'Aloo Rajma',
        description: 'Brambory s fazolemi a kari omáčkou, indická rýže nebo indické placky',
        allergen: '1,7',
        weight: '100g',
        price: 95,
        photo: 'assets/Aloo Rajma.jpg',
        packaging: 5,
    },
    {
        name: 'Lamb Kadai',
        description: 'Jehněčí kostky s jemně pálivou omáčkou, paprika, cibule, indická rýže nebo indické placky',
        allergen: '1,7',
        weight: '100g',
        price: 135,
        photo: 'assets/Lamb Kadai.jpg',
        packaging: 5,
    },
    {
        name: 'Paneer Badam Pasanda',
        description: 'Sýrové kostky s jemnou pálivou omáčkou z kokosu s mandlemi, indická rýže nebo indické placky',
        allergen: '7,8',
        weight: '100g',
        price: 95,
        photo: 'assets/Paneer Badam Pasanda.jpg',
        packaging: 5,
    },
    {
        name: 'Dal Makhani',
        description: 'Indické národní jídlo – čočka, indická rýže nebo indické placky',
        allergen: '1,7',
        weight: '100g',
        price: 95,
        photo: 'assets/Dal Makhani.jpg',
        packaging: 5,
    },
    {
        name: 'Malai Kofta',
        description: 'Opečené mleté bramborové kuličky se sýrem, oříšky a jemnou omáčkou',
        allergen: '1,7',
        weight: '100g',
        price: 95,
        photo: 'assets/Malai kofta.jpg',
        packaging: 5,
    },
    {
        name: 'Chicken Mango',
        description: 'Kuřecí kostky s jemnou omáčkou z kokosu a manga, indická rýže nebo indické placky',
        allergen: '1,7',
        weight: '100g',
        price: 100,
        packaging: 5,
        photo: 'assets/Chicken Mango.jpg',
    }
];
