import { Meal } from './meal';

export const SideDishes: Meal[] = [
    {
        name: 'Plain Rice',
        description: 'Indická rýže',
        weight: '100g',
        price: 0,
        packaging: 5,
        type: 'side',
        class: 'menu',
    },
    {
        name: 'Tandoori Chapati',
        description: 'Indická placka',
        allergen: '1',
        price: 0,
        type: 'side',
        class: 'menu',
    },
    {
        name: 'Tandoori Chapati',
        description: 'Indická základní placka',
        allergen: '1',
        packaging: 5,
        price: 25,
        type: 'side',
    },
    {
        name: 'Basmati Rice',
        description: 'Indická rýže Basmati',
        allergen: '',
        packaging: 5,
        price: 35,
        type: 'side',
    },
    {
        name: 'Tandoori Kulcha',
        description: 'Placka plněná bramborami a sýrem',
        allergen: '1',
        packaging: 5,
        price: 50,
        type: 'side',
    },
    {
        name: 'Jeera Chawal',
        description: 'Indická rýže Basmati s římským kmínem',
        allergen: '',
        packaging: 5,
        price: 35,
        type: 'side',
    },
    {
        name: 'Peas Rice',
        description: 'Indická rýže s hráškem',
        allergen: '',
        packaging: 5,
        price: 35,
        type: 'side',
    },
    {
        name: 'Tandoori Garlic Kulcha',
        description: 'Placka plněná směsí brambor a sýra s česnekem',
        allergen: '1',
        packaging: 5,
        price: 50,
        type: 'side',
    },
    {
        name: 'Tandoori Garlic Nan',
        description: 'Indická placka s česnekem',
        allergen: '1',
        packaging: 5,
        price: 40,
        type: 'side',
    },
    {
        name: 'Tandoori Punjabi Nan',
        description: 'Indická placka s oříšky',
        allergen: '1,8',
        packaging: 5,
        price: 40,
        type: 'side',
    },
    {
        name: 'Tandoori Protha',
        description: 'Indická národní placka s bylinkami',
        allergen: '1',
        packaging: 5,
        price: 40,
        type: 'side',
    },
    {
        name: 'Tandoori Nan',
        description: 'Indické placky sypané mákem a potřené ghee',
        allergen: '1',
        packaging: 5,
        price: 30,
        type: 'side',
    }
];

